### ISSUE TITLE
Validated files don't open BiRDview Applet

### ISSUE THREAD

**Issue by Robin-Aschan** [BiRD-project/BiRD_view#10]
My file successfully validated in the "BRDF json validator" tab of the BiRDview application, but when entered in the "Applet" section it wont open. By trial and error I found out that the "adhoc_variables" object is needed in the "data" object.

**Comment by Robin-Aschan-Aalto** [comment]
This ("adhoc_variables" no longer required in the "data" object) was fixed in the latest pull request.
